/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/_dev/': RouteRecordInfo<'/_dev/', '/_dev', Record<never, never>, Record<never, never>>,
    '/_dev/gl/cesium/': RouteRecordInfo<'/_dev/gl/cesium/', '/_dev/gl/cesium', Record<never, never>, Record<never, never>>,
    '/_dev/gl/cesium/index copy': RouteRecordInfo<'/_dev/gl/cesium/index copy', '/_dev/gl/cesium/index copy', Record<never, never>, Record<never, never>>,
    '/_dev/gl/three/': RouteRecordInfo<'/_dev/gl/three/', '/_dev/gl/three', Record<never, never>, Record<never, never>>,
    '/_dev/gl/three/ik/': RouteRecordInfo<'/_dev/gl/three/ik/', '/_dev/gl/three/ik', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/babylon': RouteRecordInfo<'/_dev/libBase/babylon', '/_dev/libBase/babylon', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/cesium': RouteRecordInfo<'/_dev/libBase/cesium', '/_dev/libBase/cesium', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/jsts': RouteRecordInfo<'/_dev/libBase/jsts', '/_dev/libBase/jsts', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/marked': RouteRecordInfo<'/_dev/libBase/marked', '/_dev/libBase/marked', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/mediapipe_face': RouteRecordInfo<'/_dev/libBase/mediapipe_face', '/_dev/libBase/mediapipe_face', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/mediapipe_hand': RouteRecordInfo<'/_dev/libBase/mediapipe_hand', '/_dev/libBase/mediapipe_hand', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/mediapipe_holistic': RouteRecordInfo<'/_dev/libBase/mediapipe_holistic', '/_dev/libBase/mediapipe_holistic', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/mediapipe_pose': RouteRecordInfo<'/_dev/libBase/mediapipe_pose', '/_dev/libBase/mediapipe_pose', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/monaco': RouteRecordInfo<'/_dev/libBase/monaco', '/_dev/libBase/monaco', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/opencv': RouteRecordInfo<'/_dev/libBase/opencv', '/_dev/libBase/opencv', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/opencv-video': RouteRecordInfo<'/_dev/libBase/opencv-video', '/_dev/libBase/opencv-video', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/openlayer': RouteRecordInfo<'/_dev/libBase/openlayer', '/_dev/libBase/openlayer', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/pina': RouteRecordInfo<'/_dev/libBase/pina', '/_dev/libBase/pina', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/pina-start-page/pinaOut': RouteRecordInfo<'/_dev/libBase/pina-start-page/pinaOut', '/_dev/libBase/pina-start-page/pinaOut', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/tf': RouteRecordInfo<'/_dev/libBase/tf', '/_dev/libBase/tf', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/threejs': RouteRecordInfo<'/_dev/libBase/threejs', '/_dev/libBase/threejs', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/videojs': RouteRecordInfo<'/_dev/libBase/videojs', '/_dev/libBase/videojs', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/webgl': RouteRecordInfo<'/_dev/libBase/webgl', '/_dev/libBase/webgl', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/WebGLAnimate': RouteRecordInfo<'/_dev/libBase/WebGLAnimate', '/_dev/libBase/WebGLAnimate', Record<never, never>, Record<never, never>>,
    '/[..404]': RouteRecordInfo<'/[..404]', '/:04(.*)', { 04: ParamValue<true> }, { 04: ParamValue<false> }>,
    '/blog/add': RouteRecordInfo<'/blog/add', '/blog/add', Record<never, never>, Record<never, never>>,
    '/blog/instruction': RouteRecordInfo<'/blog/instruction', '/blog/instruction', Record<never, never>, Record<never, never>>,
    '/blog/read': RouteRecordInfo<'/blog/read', '/blog/read', Record<never, never>, Record<never, never>>,
  }
}
