/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncInfoErrorPopup: typeof import('./components/app/popup/AsyncInfoErrorPopup.vue')['default']
    AsyncLoginPopup: typeof import('./components/app/popup/AsyncLoginPopup.vue')['default']
    BaseTable: typeof import('./components/common/minUi/table/BaseTable.vue')['default']
    Component: typeof import('./components/template/Component.vue')['default']
    Func_1: typeof import('./components/app/sys/head/Func_1.vue')['default']
    MinOption: typeof import('./components/common/minUi/dropdowns/min-option.vue')['default']
    MinPopover: typeof import('./components/common/minUi/button/MinPopover.vue')['default']
    MinSelect: typeof import('./components/common/minUi/dropdowns/min-select.vue')['default']
    MonacoEditor: typeof import('./components/app/edit/monacoEditor.vue')['default']
    MonacoEditorDefaut: typeof import('./components/app/edit/monacoEditorDefaut.vue')['default']
    PageInfo404: typeof import('./components/app/sampleUtils/state/PageInfo404.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowHidden: typeof import('./components/common/minUi/animation/ShowHidden.vue')['default']
    ShowHiddenMove: typeof import('./components/common/minUi/animation/ShowHiddenMove.vue')['default']
    SimplePopover: typeof import('./components/common/minUi/button/SimplePopover.vue')['default']
    StateLoading: typeof import('./components/common/minUi/animation/StateLoading.vue')['default']
    SysFooter: typeof import('./components/app/sys/SysFooter.vue')['default']
    SysHeader: typeof import('./components/app/sys/SysHeader.vue')['default']
    SysSetting: typeof import('./components/app/sys/head/SysSetting.vue')['default']
    TauriGreet: typeof import('./components/template/TauriGreet.vue')['default']
    TemplateComponent: typeof import('./components/app/sampleUtils/music/TemplateComponent.vue')['default']
    Test: typeof import('./components/app/sys/setting/test.vue')['default']
    WaitAnimate: typeof import('./components/app/sampleUtils/state/WaitAnimate.vue')['default']
  }
}
