/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseTable: typeof import('./components/minUi/table/BaseTable.vue')['default']
    MinOption: typeof import('./components/minUi/dropdowns/min-option.vue')['default']
    MinPopover: typeof import('./components/minUi/button/MinPopover.vue')['default']
    MinSelect: typeof import('./components/minUi/dropdowns/min-select.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowHidden: typeof import('./components/minUi/animation/ShowHidden.vue')['default']
    ShowHiddenMove: typeof import('./components/minUi/animation/ShowHiddenMove.vue')['default']
    SimplePopover: typeof import('./components/minUi/button/SimplePopover.vue')['default']
    StateLoading: typeof import('./components/minUi/animation/StateLoading.vue')['default']
  }
}
